### ISSUE TITLE
Google crawler follows the `?ajaxPathKey=` urls and index them

### ISSUE THREAD

**Issue by jobee** [psmb/Psmb.Ajaxify#2]
Hey @dimaip 
is there any chance to easily modify the response header in your `Psmb.Ajaxify:Renderer` ?
I would suggest `X-Robots-Tag: noindex, follow`, what do you think?

**Comment by jobee** [comment]
I came up with this workaround, please let me know whats your thoughts on that.
Was there a reason why you have skipped the default fusion response head?

```
# Override.Ajaxify.fusion
root.ajaxify.renderer = Psmb.Ajaxify:RendererWithProperResponseHead

prototype(Psmb.Ajaxify:RendererWithProperResponseHead) < prototype(Neos.Fusion:Http.Message) {
    httpResponseHead.headers {
        X-Robots-Tag = 'noindex, follow'
    }
    content = Psmb.Ajaxify:Renderer
}
```

**Comment by dimaip** [comment]
Makes sense! I think it would be good to enable it by default. Could you create a PR?

**Comment by jobee** [comment]
I will provide a PR, yes.
Any objections on the prototype naming `Psmb.Ajaxify:RendererWithProperResponseHead` ?

**Comment by jobee** [comment]
you are right, no need for an extra prototype

**Comment by dimaip** [comment]
In general having an extra prototype allows for safer extensibility at a later point, don't know if it's really justified here... Though one might want to change the tag to e.g. `noindex, nofollow` for example, and it would be better to override it based on prototype, and not just fusion path (`root.ajaxify.renderer...`)...

**Comment by jobee** [comment]
ah good point, extra prototype then
PR is created
